### PR TITLE
Shared github workflows and operator-sdk 1.31

### PR DESCRIPTION
**Pull request by dprince**
This PR switches the operator to use shared build workflows for building operator, bundle, and catalog/index images.

Additionally operator-sdk is bumped to 1.31. (also includes bump to OPM and controller-gen)

Jira: [OSP-29146](https://issues.redhat.com//browse/OSP-29146)
Jira: [OSP-26858](https://issues.redhat.com//browse/OSP-26858)

### CODE REVIEW

**Comment by gibizer** [comment]
> This PR switches the operator to use shared build workflows for building operator, bundle, and catalog/index images.
> 
> Additionally operator-sdk is bumped to 1.31. (also includes bump to OPM and controller-gen)
> 

Is there a reason to do this two seemingly independent changes (workflow, and tooling version bump) in a single commit / PR?

**Comment by dprince** [comment]
> > This PR switches the operator to use shared build workflows for building operator, bundle, and catalog/index images.
> > Additionally operator-sdk is bumped to 1.31. (also includes bump to OPM and controller-gen)
> 
> Is there a reason to do this two seemingly independent changes (workflow, and tooling version bump) in a single commit / PR?

they touch some of the same lines, and it saves CI resources

**Comment by gibizer** [comment]
> > > This PR switches the operator to use shared build workflows for building operator, bundle, and catalog/index images.
> > > Additionally operator-sdk is bumped to 1.31. (also includes bump to OPM and controller-gen)
> > 
> > 
> > Is there a reason to do this two seemingly independent changes (workflow, and tooling version bump) in a single commit / PR?
> 
> they touch some of the same lines, and it saves CI resources

In the future I would to ask to split these into multiple PRs for multiple reasons:
* easier to review if there is a single logical change
* result in a better git history: easier to find relevant commits, easier to revert one change and keep the another

**Review by gibizer — APPROVED** [review]

**Comment by gibizer** [comment]
/test placement-operator-build-deploy-kuttl
```
{  failed to wait for the created cluster claim to become ready: timed out waiting for the condition}
```

**Comment by SeanMooney** [comment]
> > > > This PR switches the operator to use shared build workflows for building operator, bundle, and catalog/index images.
> > > > Additionally operator-sdk is bumped to 1.31. (also includes bump to OPM and controller-gen)
> > > 
> > > 
> > > Is there a reason to do this two seemingly independent changes (workflow, and tooling version bump) in a single commit / PR?
> > 
> > 
> > they touch some of the same lines, and it saves CI resources
> 
> In the future I would to ask to split these into multiple PRs for multiple reasons:
> 
>     * easier to review if there is a single logical change
> 
>     * result in a better git history: easier to find relevant commits, easier to revert one change and keep the another

in general i agree don't combine just to save job time.

**Pull request merged**
