### PR TITLE
Bump golang to 1.21

### PR DESCRIPTION
**Pull request by mrkisaolamb**
Jira: [OSPRH-9448](https://issues.redhat.com//browse/OSPRH-9448)

### CODE REVIEW

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by gibizer** [comment]
/test placement-operator-build-deploy-kuttl
```
  *[2024-09-24T15:47:43Z]NoClusters: No clusters in pool are ready to be claimed 
```

**Review by dprince — APPROVED** [review]

**Pull request merged**
