### PR TITLE
Rename apiEndpoint key for consistency

### PR DESCRIPTION
**Pull request by kajinamit**
Currently some operators use apiEndpoints(plural) while the other use apiEndpoint(singular). This is quite confusing and requires users to check which key is presented by a operator, to obtain the same information.

This renames the key to the plural, because this status field is a map which can contain multiple endpoints.

### CODE REVIEW

**Comment by kajinamit** [comment]
Hmm. I noticed operators exposing APIEndpoints contain service type as top-level key. We probably have to consider adding that as well ?

**Comment by bogdando** [comment]
Shouldn't we poke the major API version each time we introduce such a breaking change?

**Comment by SeanMooney** [comment]
> Shouldn't we poke the major API version each time we introduce such a breaking change (or will we have to start doing that after the dev preview)?

yes but we have not started doing that yet

once we do the first deve preview release we should enforce that

**Comment by SeanMooney** [comment]
> Hmm. I noticed operators exposing APIEndpoints contain service type as top-level key. We probably have to consider adding that as well ?

i would need more context for that that is used for to answer that.

in general we do not want to allow an interface to customise if the service we create are clusterip or nodeport or loadbalancer.

this is meant to be determined by if you use network attachmetns or not

**Comment by kajinamit** [comment]
>  i would need more context for that that is used for to answer that.

Some operators need to deploy multiple api endpoints (ironic-api and ironic-doncuttor-api/ heat-api and heat-cfn-api ) and these operators expose multiple endpoints and the status field contains these with top-level key to explain the service using that endpoint (eg. `{'heat-api': {'internal': <heat api internal url>, 'public': <heat api public url>}, 'heat-cfn-api': {'internal': <heat cfn internal url>, 'public': <heat cfn public url>}`)

Also, giving another thought to this topic, I'm not too sure about the benefit of expising APIEndpoint in status field. Usually service endpoints(except for keystone endpoints) can be discovered by keystone catalog api and that's what we've been using in client. We can probably even remove the fields if we are not aware of actual use case.

Anyway I'll bring this to next sync for further discussion.

**Comment by kajinamit** [comment]
> > Shouldn't we poke the major API version each time we introduce such a breaking change (or will we have to start doing that after the dev preview)?
> 
> yes but we have not started doing that yet
> 
> once we do the first deve preview release we should enforce that

I'm not too sure if we have to ensure api compatibility even after dev preview. The aim of dev preview is mostly to get some feedback (IIUC) but I might be wrong. This is another topic we can discuss further (in a different channel, not here).

**Comment by gibizer** [comment]
> > i would need more context for that that is used for to answer that.
> 
> Some operators need to deploy multiple api endpoints (ironic-api and ironic-doncuttor-api/ heat-api and heat-cfn-api ) and these operators expose multiple endpoints and the status field contains these with top-level key to explain the service using that endpoint (eg. `{'heat-api': {'internal': <heat api internal url>, 'public': <heat api public url>}, 'heat-cfn-api': {'internal': <heat cfn internal url>, 'public': <heat cfn public url>}`)
> 
> Also, giving another thought to this topic, I'm not too sure about the benefit of expising APIEndpoint in status field. Usually service endpoints(except for keystone endpoints) can be discovered by keystone catalog api and that's what we've been using in client. We can probably even remove the fields if we are not aware of actual use case.
> 
> Anyway I'll bring this to next sync for further discussion.

Thanks @kajinamit . I tend to agree that we should remove this and let the end user discover this via the keystone API.

**Comment by kajinamit** [comment]
Based on the feedback in the previous sync call, I'll remove this key because the presented information is not much useful.

**Pull request closed without merging**
