### PR TITLE
Move CRD utils to lib-common

### PR DESCRIPTION
**Pull request by gibizer**
Lets use the CRD helpes from lib-common.

### CODE REVIEW

**Comment by gibizer** [comment]
We need https://github.com/openstack-k8s-operators/lib-common/pull/26 to lend first, until that this will be red

**Comment by stuggi** [comment]
@gibizer sorry, somehow missed that, could you rebase this. we can then land it

**Comment by gibizer** [comment]
Rebased. Dependencies has been merged so this is good to go.

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
