### PR TITLE
Placement: use KeystoneService

### PR DESCRIPTION
**Pull request by slagle**
Updates the Placement controller to use the KeystoneService API for setting
up Keystone resources for Placement.

Signed-off-by: James Slagle <jslagle@redhat.com>

### CODE REVIEW

**Review by stuggi — CHANGES_REQUESTED** [review]
the operator needs permission to create, list, watch and update keystoneservices resources in API group keystone.openstack.org

**Comment by slagle** [comment]
> the operator needs permission to create, list, watch and update keystoneservices resources in API group keystone.openstack.org

**Review by stuggi — APPROVED** [review]
lgtm

**Comment by stuggi** [comment]
I pushed new image which has this patch quay.io/openstack-k8s-operators/placement-operator:v0.0.2

**Pull request merged**
