### PR TITLE
update finalzier to CRD doc

### PR DESCRIPTION
**Pull request by stuggi**
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/519
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/231

### CODE REVIEW

**Review by mrkisaolamb — COMMENTED** [review]
lokk ok for me but we need to wait for https://github.com/openstack-k8s-operators/mariadb-operator/pull/231

**Comment by stuggi** [comment]
> lokk ok for me but we need to wait for [openstack-k8s-operators/mariadb-operator#231](https://github.com/openstack-k8s-operators/mariadb-operator/pull/231)

right, will do the rest of the PRs tomorrow, as they all/most of them have the dep.

**Review by gibizer — COMMENTED** [review]
Thanks @stuggi. Looks good. We can land it as soon as the deps lands.

**Review by abays — APPROVED** [review]
/lgtm

**Review by mrkisaolamb — APPROVED** [review]

**Pull request merged**
