### PR TITLE
Replace TripleO images by TCIB images

### PR DESCRIPTION
**Pull request by kajinamit**
We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.

[1] https://github.com/openstack-k8s-operators/tcib

### CODE REVIEW

**Comment by gibizer** [comment]
@kajinamit I rebased this PR to the webhook work that moved the default ContainerImage to an env variable. Could you please check that this look OK from your perspective?

**Comment by SeanMooney** [comment]
should we just swap to antelope at this point?
we will need to do that sonner rater then later.

the images already exist and i would prefer to avoid changing these twice in a few weeks
https://quay.io/organization/podified-antelope-centos9

**Comment by kajinamit** [comment]
> @kajinamit I rebased this PR to the webhook work that moved the default ContainerImage to an env variable. Could you please check that this look OK from your perspective?

Thanks. It looks good to me. I didn't push these replacement patches because kuttl tests fail unless we remove hard-code in install_yamls but it seems placement-operator is not affected because kuttl tests are not yet added so we are good.

**Comment by kajinamit** [comment]
> should we just swap to antelope at this point? we will need to do that sonner rater then later.
> 
> the images already exist and i would prefer to avoid changing these twice in a few weeks https://quay.io/organization/podified-antelope-centos9

I think we can skip zed and wait for antelope. afaik rdo antelope is still being prepared so we probably have wait for another week to get the new images built with antelope packages but I'll double check it.

**Comment by gibizer** [comment]
I'm OK to wait for the proper antelope packages.

**Comment by kajinamit** [comment]
I confirmed these podified-antelope-centos9 images are built from RDO antelope packages so we can use these now.

**Comment by gibizer** [comment]
I was able to run the antelope placement now:

```
$ openstack trait list | grep COMPUTE_SHARE_LOCAL_FS
| COMPUTE_SHARE_LOCAL_FS                |
```

**Review by gibizer — APPROVED** [review]
I think this is good to go

**Pull request merged**
