### PR TITLE
[envtest]Cover reconfiguration cases

### PR DESCRIPTION
**Pull request by gibizer**
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/337 (merged)
Depends-On: https://github.com/openstack-k8s-operators/placement-operator/pull/63 (merged)
Related: https://issues.redhat.com/browse/OSPRH-108

### CODE REVIEW

**Comment by gibizer** [comment]
kuttl failure seems relevant, something in the lib-common bump causing wrong endpoint naming:
```
    logger.go:42: 13:15:50 | placement_scale/2-patch_placement_deploy | Regex check 'http:\/\/placement-internal\..+\.svc.*' failed against oc output: http://://placement-internal.placement-kuttl-tests.svc:8778:http://://placement-public-placement-kuttl-tests.apps.oko-13.oooci.ccitredhat.com:8778
```

**Comment by gibizer** [comment]
> kuttl failure seems relevant, something in the lib-common bump causing wrong endpoint naming:
> 
> ```
>     logger.go:42: 13:15:50 | placement_scale/2-patch_placement_deploy | Regex check 'http:\/\/placement-internal\..+\.svc.*' failed against oc output: http://://placement-internal.placement-kuttl-tests.svc:8778:http://://placement-public-placement-kuttl-tests.apps.oko-13.oooci.ccitredhat.com:8778
> ```

adapting to the new lib-common change is more complicated than I anticipated. It is probably better to wait for https://github.com/openstack-k8s-operators/placement-operator/pull/61 to land and then rebase this after.

**Comment by gibizer** [comment]
> > kuttl failure seems relevant, something in the lib-common bump causing wrong endpoint naming:
> > ```
> >     logger.go:42: 13:15:50 | placement_scale/2-patch_placement_deploy | Regex check 'http:\/\/placement-internal\..+\.svc.*' failed against oc output: http://://placement-internal.placement-kuttl-tests.svc:8778:http://://placement-public-placement-kuttl-tests.apps.oko-13.oooci.ccitredhat.com:8778
> > ```
> 
> adapting to the new lib-common change is more complicated than I anticipated. It is probably better to wait for #61 to land and then rebase this after.

#61 landed and this is rebased so no need to lib-common bump

**Comment by gibizer** [comment]
/unhold
dependencies landed

**Review by mrkisaolamb — APPROVED** [review]
lgtm

**Pull request merged**
